name: Annotate CI run with Tests Results
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  annotate:
    name: Annotate CI run with Tests Results
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Annotate CI run with Tests Results
        uses: dorny/test-reporter@v1.5.0
        with:
          artifact: tests-result
          name: Tests Results
          path: "*.xml"
          reporter: java-junit
          list-suites: 'all'
          list-tests: 'all'
